### ISSUE TITLE
Declare babel-polyfill as dependency or peerDependency

### ISSUE THREAD

**Issue by eliperelman** [guigrpa/oao#1]
Right now just doing an installation of oao and running it throws an error:

```text
❯ ./node_modules/.bin/oao bootstrap
module.js:471
    throw err;
    ^

Error: Cannot find module 'babel-polyfill'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/eli/code/neutrino-dev/node_modules/oao/lib/index.js:4:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Looking at the code, it is indeed looking for babel-polyfill in the compiled code, but it's only listed as a dev dependency. This should be either a dependency or peer dependency.

**Comment by guigrpa** [comment]
Thanks for reporting! Corrected in the latest release.

If you use oao, please send me your feedback!

**Comment by eliperelman** [comment]
@guigrpa will do! I've got a PR open to start using it for https://github.com/mozilla-neutrino/neutrino-dev

Thanks!
