### ISSUE TITLE
status command throws "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by mdreizin** [guigrpa/oao#31]
Currently status command throws the following error:

```
TypeError: Cannot read property 'length' of undefined
    at field (/Users/mdreizin/.config/yarn/global/node_modules/oao/lib/status.js:227:10)
    at _callee3$ (/Users/mdreizin/.config/yarn/global/node_modules/oao/lib/status.js:177:51)
    at tryCatch (/Users/mdreizin/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:64:40)
    at Generator.invoke [as _invoke] (/Users/mdreizin/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:299:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/mdreizin/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:116:21)
    at step (/Users/mdreizin/.config/yarn/global/node_modules/oao/lib/status.js:13:191)
    at /Users/mdreizin/.config/yarn/global/node_modules/oao/lib/status.js:13:361
```

**Comment by guigrpa** [comment]
Thanks
