### ISSUE TITLE
oao equivalent of yarn upgrade-interactive?

### ISSUE THREAD

**Issue by ericclemmons** [guigrpa/oao#49]
Both `yarn outdated` and `yarn upgrade-interactive` return **Outdated lockfile. Please run `yarn install` and try again.**, likely do to the oao dependencies.

`oao upgrade` seems to bail with an error on the 1st outdated package.

```
 ❯ oao all "yarn upgrade-interactive"
2017-08-30T15:44:00.857Z           storyboard INFO  ┌── ROOT STORY: null, SB 3.1.1 [CREATED]
2017-08-30T15:44:00.858Z           storyboard INFO  Log filter: *:DEBUG
2017-08-30T15:44:01.168Z                 main INFO  ┌── Run cmd yarn upgrade-interactive at examples/with-404 [CREATED]
2017-08-30T15:44:01.393Z                 yarn INFO  yarn upgrade-interactive v0.27.5
2017-08-30T15:44:01.527Z                 yarn ERROR error Outdated lockfile. Please run `yarn install` and try again.
2017-08-30T15:44:01.527Z                 yarn INFO  info Visit https://yarnpkg.com/en/docs/cli/upgrade-interactive for documentation about this command.
2017-08-30T15:44:01.537Z                 yarn INFO
2017-08-30T15:44:01.541Z                 main ERROR Command 'yarn upgrade-interactive' failed at examples/with-404
                                         main ERROR   name: 'Error'
                                         main ERROR   message: Command failed: /bin/sh -c yarn upgrade-interactive
                                         main ERROR   message: error Outdated lockfile. Please run `yarn install` and try again.
                                         main ERROR   message: yarn upgrade-interactive v0.27.5
                                         main ERROR   message: info Visit https://yarnpkg.com/en/docs/cli/upgrade-interactive for documentation about this command.
                                         main ERROR   message:
                                         main ERROR   stack: Error: Command failed: /bin/sh -c yarn upgrade-interactive
                                         main ERROR   stack: error Outdated lockfile. Please run `yarn install` and try again.
                                         main ERROR   stack: yarn upgrade-interactive v0.27.5
                                         main ERROR   stack: info Visit https://yarnpkg.com/en/docs/cli/upgrade-interactive for documentation about this command.
                                         main ERROR   stack:
                                         main ERROR   stack:     at Promise.all.then.arr (/Users/eric/.config/yarn/global/node_modules/execa/index.js:210:11)
                                         main ERROR   stack:     at process._tickCallback (internal/process/next_tick.js:109:7)
2017-08-30T15:44:01.543Z                 main INFO  └── Run cmd yarn upgrade-interactive at examples/with-404 [CLOSED]
```

**Comment by guigrpa** [comment]
Instead of `yarn outdated`, you may want to check out `oao outdated`.

Regarding `oao all "xxx"`, by default it bails out on the first error. You can use `oao all --ignore-errors "xxx"` to avoid that. 

Finally, regarding `yarn upgrade-interactive`, I don't think it is or will be compatible with oao, *unless* you switch to Yarn Workspaces, for which support is included in the latest version of oao. Have you considered this? Under workspaces:

* There is a single `yarn.lock` file, at the root
* `oao bootstrap` becomes equivalent to `yarn install`
* `package.json` files are untouched by oao during bootstrap or dep add/remove/upgrade
* All other yarn subcommands (`outdated`, `upgrade-interactive`, etc.) should work as expected

**Comment by ericclemmons** [comment]
@guigrpa Thanks for the writeup.  I'll check out the latest version of `oao` then.  Closing in the meantime :)

**Comment by ericclemmons** [comment]
I was able to get workspaces working, but it has it's own set of issues unrelated to `oao`: 
- #4442
- #4469
