### ISSUE TITLE
Problem with yarn workspaces declaration in version 1.5.1

### ISSUE THREAD

**Issue by zhDmitry** [guigrpa/oao#71]
``^^/D/test-git >>> oao outdated                          
        storyboard INFO  ┌── ROOT STORY: Node.js 8.9.1 on Darwin 64-bit, SB 3.1.3 [CREATED]
2018-03-03T10:50:19.818Z           storyboard INFO  Log filter: *:DEBUG
TypeError: patterns must be a string or an array of strings
    at assertPatternsInput (/usr/local/lib/node_modules/oao/node_modules/globby/index.js:20:9)
    at generateGlobTasks (/usr/local/lib/node_modules/oao/node_modules/globby/index.js:26:2)
    at module.exports (/usr/local/lib/node_modules/oao/node_modules/globby/index.js:62:15)
    at _callee$ (/usr/local/lib/node_modules/oao/lib/utils/listPaths.js:34:41)
    at tryCatch (/usr/local/lib/node_modules/oao/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/oao/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/oao/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/lib/node_modules/oao/lib/utils/listPaths.js:21:191)
    at /usr/local/lib/node_modules/oao/lib/utils/listPaths.js:21:437
    at new Promise (<anonymous>)
2018-03-03T10:50:20.144Z    ``

check out this example https://github.com/dmytroZherebko/oao-test
try to run 
`
oao status
`
`
oao outdated
`

**Comment by anthonyjlmorel** [comment]
Same here. The last yarn wokspaces stuff is highly needed, and oao seems pretty awesome to help us managing our monorepo.

I am looking forward to seeing this fixed !

Great job guys.

**Comment by guigrpa** [comment]
Will be fixed in the next release. Thanks for the example repo, it was really helpful!

**Comment by anthonyjlmorel** [comment]
Could you tell us when will that be ? Just to put a reminder :)

**Comment by guigrpa** [comment]
Shipped around 5 min after I told you :)
